class_jmlr(crammer01a).
class_jmlr(pekalska01a).
class_jmlr(megyesi02a).
class_jmlr(bongard05a).
class_jmlr(dhillon03a).
class_jmlr(bengio03a).
class_jmlr(agarwal05a).
class_jmlr(cortes04a).
class_jmlr(bi03a).
class_jmlr(goldsmith05a).
