class_jmlr(gretton05a).
class_jmlr(wolf05a).
class_jmlr(jaeger05a).
class_jmlr(ling02a).
class_jmlr(rakotomamonjy05a).
class_jmlr(steinwart05a).
class_jmlr(cancedda03a).
class_jmlr(ginter04a).
class_jmlr(eibl05a).
class_jmlr(bekkerman03a).
