stopword('aggettivo').
stopword('ad').
stopword('al').
stopword('allo').
stopword('ai').
stopword('agli').
stopword('all').
stopword('agl').
stopword('alla').
stopword('alle').
stopword('con').
stopword('col').
stopword('coi').
stopword('da').
stopword('dal').
stopword('dallo').
stopword('dai').
stopword('dagli').
stopword('dall').
stopword('dagl').
stopword('dalla').
stopword('dalle').
stopword('di').
stopword('del').
stopword('dello').
stopword('dei').
stopword('degli').
stopword('dell').
stopword('degl').
stopword('della').
stopword('delle').
stopword('in').
stopword('nel').
stopword('nello').
stopword('nei').
stopword('negli').
stopword('nell').
stopword('negl').
stopword('nella').
stopword('nelle').
stopword('su').
stopword('sul').
stopword('sullo').
stopword('sui').
stopword('sugli').
stopword('sull').
stopword('sugl').
stopword('sulla').
stopword('sulle').
stopword('per').
stopword('tra').
stopword('contro').
stopword('io').
stopword('tu').
stopword('lui').
stopword('lei').
stopword('noi').
stopword('voi').
stopword('loro').
stopword('mio').
stopword('mia').
stopword('miei').
stopword('mie').
stopword('tuo').
stopword('tua').
stopword('tuoi').
stopword('tue').
stopword('suo').
stopword('sua').
stopword('suoi').
stopword('sue').
stopword('nostro').
stopword('nostra').
stopword('nostri').
stopword('nostre').
stopword('vostro').
stopword('vostra').
stopword('vostri').
stopword('vostre').
stopword('mi').
stopword('ti').
stopword('ci').
stopword('vi').
stopword('lo').
stopword('la').
stopword('li').
stopword('le').
stopword('gli').
stopword('ne').
stopword('il').
stopword('un').
stopword('uno').
stopword('una').
stopword('ma').
stopword('ed').
stopword('se').
stopword('perché').
stopword('anche').
stopword('come').
stopword('dov').
stopword('dove').
stopword('che').
stopword('chi').
stopword('cui').
stopword('non').
stopword('più').
stopword('quale').
stopword('quanto').
stopword('quanti').
stopword('quanta').
stopword('quante').
stopword('quello').
stopword('quelli').
stopword('quella').
stopword('quelle').
stopword('questo').
stopword('questi').
stopword('questa').
stopword('queste').
stopword('si').
stopword('tutto').
stopword('tutti').
stopword('a').
stopword('c').
stopword('e').
stopword('i').
stopword('l').
stopword('o').
stopword('ho').
stopword('hai').
stopword('ha').
stopword('abbiamo').
stopword('avete').
stopword('hanno').
stopword('abbia').
stopword('abbiate').
stopword('abbiano').
stopword('avrò').
stopword('avrai').
stopword('avrà').
stopword('avremo').
stopword('avrete').
stopword('avranno').
stopword('avrei').
stopword('avresti').
stopword('avrebbe').
stopword('avremmo').
stopword('avreste').
stopword('avrebbero').
stopword('avevo').
stopword('avevi').
stopword('aveva').
stopword('avevamo').
stopword('avevate').
stopword('avevano').
stopword('ebbi').
stopword('avesti').
stopword('ebbe').
stopword('avemmo').
stopword('aveste').
stopword('ebbero').
stopword('avessi').
stopword('avesse').
stopword('avessimo').
stopword('avessero').
stopword('avendo').
stopword('avuto').
stopword('avuta').
stopword('avuti').
stopword('avute').
stopword('sono').
stopword('sei').
stopword('è').
stopword('siamo').
stopword('siete').
stopword('sia').
stopword('siate').
stopword('siano').
stopword('sarò').
stopword('sarai').
stopword('sarà').
stopword('saremo').
stopword('sarete').
stopword('saranno').
stopword('sarei').
stopword('saresti').
stopword('sarebbe').
stopword('saremmo').
stopword('sareste').
stopword('sarebbero').
stopword('ero').
stopword('eri').
stopword('era').
stopword('eravamo').
stopword('eravate').
stopword('erano').
stopword('fui').
stopword('fosti').
stopword('fu').
stopword('fummo').
stopword('foste').
stopword('furono').
stopword('fossi').
stopword('fosse').
stopword('fossimo').
stopword('fossero').
stopword('essendo').
stopword('faccio').
stopword('fai').
stopword('facciamo').
stopword('fanno').
stopword('faccia').
stopword('facciate').
stopword('facciano').
stopword('farò').
stopword('farai').
stopword('farà').
stopword('faremo').
stopword('farete').
stopword('faranno').
stopword('farei').
stopword('faresti').
stopword('farebbe').
stopword('faremmo').
stopword('fareste').
stopword('farebbero').
stopword('facevo').
stopword('facevi').
stopword('faceva').
stopword('facevamo').
stopword('facevate').
stopword('facevano').
stopword('feci').
stopword('facesti').
stopword('fece').
stopword('facemmo').
stopword('faceste').
stopword('fecero').
stopword('facessi').
stopword('facesse').
stopword('facessimo').
stopword('facessero').
stopword('facendo').
stopword('sto').
stopword('stai').
stopword('sta').
stopword('stiamo').
stopword('stanno').
stopword('stia').
stopword('stiate').
stopword('stiano').
stopword('starò').
stopword('starai').
stopword('starà').
stopword('staremo').
stopword('starete').
stopword('staranno').
stopword('starei').
stopword('staresti').
stopword('starebbe').
stopword('staremmo').
stopword('stareste').
stopword('starebbero').
stopword('stavo').
stopword('stavi').
stopword('stava').
stopword('stavamo').
stopword('stavate').
stopword('stavano').
stopword('stetti').
stopword('stesti').
stopword('stette').
stopword('stemmo').
stopword('steste').
stopword('stettero').
stopword('stessi').
stopword('stesse').
stopword('stessimo').
stopword('stessero').
stopword('stando').
