class_jmlr(kim05a).
class_jmlr(langford05a).
class_jmlr(bordes05a).
class_jmlr(khardon05a).
class_jmlr(kitzelmann06a).
class_jmlr(califf03a).
class_jmlr(spratling06a).
class_jmlr(keerthi05a).
class_jmlr(stoppiglia03a).
class_jmlr(chen04a).
